openapi: 3.0.0
info:
  title: "Hydrocron"
  description: "Get time series data from SWOT observations for reaches and nodes"
  version: ${software_version}
servers:
- url: https://virtserver.swaggerhub.com/hydrocron/${api_version}
  description: "Get time series data from SWOT observations for reaches and nodes"
paths:
  /timeseries:
    get:
      summary: "Get Timeseries for a particular Reach, Node, or LakeID"
      description: "Get Timeseries for a particular Reach, Node, or LakeID"
      operationId: timeseries_get
      security:
      - api-key-auth: []
        ${authorizer_name}: []
      parameters:
      - name: feature
        in: query
        description: Type of feature being requested
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum: [ "Reach", "Node"]
        example: Reach
      - name: feature_id
        in: query
        description: ID of the feature to retrieve in format CBBTTTSNNNNNN (i.e. 74297700000000)
        required: true
        style: form
        explode: true
        schema:
          type: string
        example: 71224100223
      - name: start_time
        in: query
        description: Start time of the timeseries
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date-time
        example: 2022-08-04T00:00:00Z
      - name: end_time
        in: query
        description: End time of the timeseries
        required: true
        style: form
        explode: true
        schema:
          type: string
          format: date-time
        example: 2022-08-23T00:00:00Z
      - name: output
        in: query
        description: Format of the data returned
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum: [ "csv", "geojson"]
          default: geojson
        example: geojson
      - name: fields
        in: query
        description: Format of the data returned
        required: true
        style: form
        explode: true
        schema:
          type: string
          default: feature_id, time_str, wse, geometry
        example: feature_id, time_str, wse, geometry
      - name: compact
        in: query
        description: Whether to return a compact GeoJSON response
        required: false
        schema:
          type: boolean
          default: false
        example: true
      responses:
        "200":
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/json'
            text/csv:
              schema:
                $ref: '#/components/schemas/csv'
            application/geo+json:
              schema:
                $ref: '#/components/schemas/geojson'
        "400":
          description: "400 error. The specified URL is invalid (does not exist)."
          content:
            text/csv:
              schema:
                type: array
                items:
                  type: string
        "404":
          description: "404 error. An entry with the specified region was not found."
          content:
            text/csv:
              schema:
                type: array
                items:
                  type: string
        "413":
          description: "413 error. Your query has returned is too large."
          content:
            text/csv:
              schema:
                type: array
                items:
                  type: string
        "415":
          description: "415 error. Your request includes an unsupported media type."
          content:
            text/csv:
              schema:
                type: array
                items:
                  type: string
      x-openapi-router-controller: hydrocron_api.controllers.timeseries

      x-amazon-apigateway-integration:
        uri: ${hydrocron_api_lambda_arn_timeseries}
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            responseTemplates:
              application/json: |
                #set($inputRoot = $input.path('$'))
                #if($inputRoot.toString().contains('206 PARTIAL CONTENT'))
                  #set($context.responseOverride.status = 206)
                #end
                $input.json('$')
              application/geo+json: |
                #set($inputRoot = $input.path('$'))
                #if($inputRoot.toString().contains('206 PARTIAL CONTENT'))
                  #set($context.responseOverride.status = 206)
                #end
                $input.json('$')
              text/csv: |
                #set($inputRoot = $input.path('$'))
                #if($inputRoot.toString().contains('206 PARTIAL CONTENT'))
                  #set($context.responseOverride.status = 206)
                #end
                $input.body
          ^400.*:
            statusCode: "400"
            responseTemplates:
              application/json: |-
                {
                  "error" : "$input.path('$.errorMessage')"
                }
          ^404.*:
            statusCode: "404"
            responseTemplates:
              application/json: |-
                {
                  "error" : "$input.path('$.errorMessage')"
                }
          ^413.*:
            statusCode: "413"
            responseTemplates:
              application/json: |-
                {
                  "error" : "$input.path('$.errorMessage')"
                }
          ^415.*:
            statusCode: "415"
            responseTemplates:
              application/json: |-
                {
                  "error" : "$input.path('$.errorMessage')"
                }
          ^[^1-5].*:
            statusCode: "500"
            responseTemplates:
              application/json: |-
                {
                  "error" : "$input.path('$.errorMessage')"
                }
        requestTemplates:
          application/json: |-
            #set($queryParams = $input.params().querystring)
            #set($headerParams = $input.params().header)
            {
              "body" :
              {
                #foreach($paramName in $queryParams.keySet())
                "$paramName": "$util.escapeJavaScript($queryParams.get($paramName))"
                  #if($foreach.hasNext),#end
                #end
              },
              "headers" : 
              {
                #foreach($header in $headerParams.keySet())
                "$header": "$util.escapeJavaScript($input.params().header.get($header))" 
                  #if($foreach.hasNext),#end
                #end
              }
            }
        passthroughBehavior: when_no_templates
        httpMethod: POST
        contentHandling: CONVERT_TO_TEXT
        type: aws
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      tags:
      - CORS
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods: "'*'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
x-amazon-apigateway-api-key-source: "AUTHORIZER"
components:
  schemas:
    json:
      type: object
    geojson:
      type: object
    csv:
      type: object
  securitySchemes:
    api-key-auth:
      type: apiKey
      in: header       
      name: x-api-key
    ${authorizer_name}:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authorizer:
        type: request
        identitySource: method.request.header.User-Agent
        authorizerUri: ${authorizer_url}
        authorizerCredentials: ${authorizer_credentials}
        authorizerPayloadFormatVersion: '1.0'
        authorizerResultTtlInSeconds: 0
      x-amazon-apigateway-authtype: custom