services:
  dynamodb-local:
#    Uncomment if data should be persisted between container restarts
#    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
#    volumes:
#      - "./docker/dynamodb:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8001:8000"
    working_dir: /home/dynamodblocal
    networks:
      - hydrocron
  hydrocron-table-create:
    image: "amazon/aws-cli"
    container_name: hydrocron-table-create
    entrypoint: /bin/sh -c
    command: >
      "echo 'Tables will be created by load_data_local.py - skipping'"
    depends_on:
      - dynamodb-local
    networks:
      - hydrocron
    environment:
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      AWS_DEFAULT_REGION: us-west-2
  hydrocron-lambda:
    image: "hydrocron:latest"
    container_name: hydrocron-lambda
    ports:
      - "9000:8080"
    depends_on:
      - hydrocron-table-create
    networks:
      - hydrocron
    environment:
      HYDROCRON_ENV: LOCAL
      HYDROCRON_dynamodb_endpoint_url: http://host.docker.internal:8001
      AWS_ACCESS_KEY_ID: fakeMyKeyId
      AWS_SECRET_ACCESS_KEY: fakeSecretAccessKey
      AWS_DEFAULT_REGION: us-west-2
      DEFAULT_RIVER_COLLECTION: SWOT_L2_HR_RiverSP
      DEFAULT_LAKE_COLLECTION: SWOT_L2_HR_LakeSP
      DEFAULT_COLLECTION_VERSION: D
  hydrocron-apigw:
    build:
      context: ./docker
      dockerfile: Dockerfile.local_apigw
    container_name: hydrocron-apigw
    ports:
      - "8080:8080"
    depends_on:
      - hydrocron-lambda
    networks:
      - hydrocron
    environment:
      LAMBDA_URL: http://hydrocron-lambda:8080/2015-03-31/functions/function/invocations
networks:
  hydrocron: {}